config/routes.rb
Rails.application.routes.draw do
  get "upcoming" => "events#index"

  root 'events#index'

  resources :events do
    resources :tickets
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_inclusion_of :name, in: ['Entertainment', 'Learning', 'Everything Else']
  validates_uniqueness_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  belongs_to :category
  has_many :ticket_types

  validates_presence_of :extended_html_description, :venue, :category, :starts_at
  validates_uniqueness_of :name, uniqueness: {scope: [:venue, :starts_at]}

  def self.upcoming
    Event.where("ends_at > ?", Time.now)
  end
end

app/models/region.rb
class Region < ActiveRecord::Base
    validates_inclusion_of :name, in: ['Ho Chi Minh', 'Ha Noi', 'Binh Thuan', 'Da Nang', 'Lam Dong']
    validates_uniqueness_of :name
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  belongs_to :event
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :region
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def header_background_image_url
    image_path('color-me-run.jpg')
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_card.html.erb
<div class="col-md-6">
  <%= link_to event_path(event) do %>
    <div class="card">
      <img class="card-img-top" src="<%= event.hero_image_url %>">
      <div class="card-block">
        <h4 class="card-title"><%= event.name %></h4>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.
        </p>
      </div>
    </div>
  <% end %>
</div>  

app/views/events/index.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Discover upcoming events </h2>
    <form>
      <input type="text" class="form-control" name="search" placeholder="Search for events, shows, courses...">
    </form>
  </div>
</div>
<div class="container-fluid events-list">
    <% @events.in_groups_of(3) do |g| %>
      <div class="row">
        <% g.compact.each do |e| %>
            <%= render partial: 'card', locals: {event: e} %>
        <% end %>
      </div>  
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid no-pad events-detail">
  <div class="row no-pad">
    <div class="col-md-3 sidebar">
      <p>
        <%= fa_icon 'ticket' %>
        Price
      </p>
      <h1> Hot Events </h1>
      <div class="ticket-list">
        <% @event.ticket_types.each do |ticket_type| %>
          <div class="row">
            <div class="col-md-6">
              <%= ticket_type.name %>
            </div>

            <div class="col-md-6 price text-right">
              <%= number_to_currency(ticket_type.price, unit: 'VND', precision: 0) %>
            </div>
          </div>
          <div class="clearfix"></div>
        <% end %>
        <%= link_to new_event_ticket_path(@event) do %>
          <button class='btn btn-lg btn-block btn-danger'> BOOK NOW </button>
        <% end %>
      </div>
    </div>
    <div class="col-md-9 event-content">
      <div class="hero-img hidden-sm-down" style="background-image: url(<%= @event.hero_image_url %>); background-size: cover;"> </div>
      <div class="container">
        <h3> <%= @event.name %> </h3>
        <div class="pull-left">
          <%= fa_icon 'clock-o' %>
        </div>
        <div class="time-details"> 
          <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %> 
        </div>

        

        <div class="pull-left">
          <%= fa_icon 'map-marker' %>
        </div>
        <div class="venue-details">
         <%= @event.venue.name %>
         <br/>
         <%= @event.venue.full_address %>
        </div>

        <div class="img-spacer">
          <%= image_tag 'shadow-top.png' %>
        </div>
        <div class="extended-description">
          <%= @event.extended_html_description.html_safe %>
        </div>

      </div>  
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsTemplate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <a class="navbar-brand" href="<%= root_path %>">Coder Ticket</a>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Log In</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sign Up</a>
      </li>
    </ul>
  </nav>  

<%= yield %>

</body>
</html>

app/views/tickets/new.html.erb
<div class="container-fluid tickets-buy">
  <div class="row tickets-header">
    <div class="col-xs-12 col-md-11 col-md-offset-1">
      <h3> <%= @event.name %> </h3>
      <div class="pull-left">
        <%= fa_icon 'map-marker' %>
      </div>
      <div class="venue-details">
       <%= @event.venue.name %>
       <br/>
       <%= @event.venue.full_address %>
      </div>

      <div class="pull-left">
        <%= fa_icon 'clock-o' %>
      </div>
      <div class="time-details"> 
        <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %> 
      </div>


    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-md-offset-1">  
      <table class="table">
        <th> Ticket Type </th>
        <th> Unit Price </th>
        <th> Quantity </th>
      
        <% @event.ticket_types.each do |type| %>
        <tr>
          <td> <%= type.name %> </td>
          <td> <%= number_to_currency(type.price, unit: 'VND ', precision: 0) %> </td>
          <td> <%= select_tag('quantity', options_for_select(0..10)) %></td> 
        </tr>
        <% end %> 
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 col-md-offset-5">
      <button class="btn btn-success btn-lg btn-block"> Buy </button>
    </div>
  <div>
</div>  